### ISSUE TITLE
ZeroDivisionError: division by zero on adafruit_tcs34725.py

### ISSUE THREAD

**Issue by asidroid** [adafruit/Adafruit_CircuitPython_TCS34725#14]
On /usr/local/lib/python3.5/dist-packages/adafruit_tcs34725.py the function `def color_rgb_bytes(self)` should check if rgb values are greater than zero to avoid the division by zero exception

File "/usr/local/lib/python3.5/dist-packages/adafruit_tcs34725.py", line 240, in color_rgb_bytes
    red   = int(pow((int((r/clear) * 256) / 255), 2.5) * 255)
ZeroDivisionError: division by zero

**Comment by caternuson** [comment]
@ladyada This is touching on the same part of the code that I stumbled upon in #10. Do you happen to have any insight as to where that math is coming from and/or what it's trying to do?
https://github.com/adafruit/Adafruit_CircuitPython_TCS34725/blob/master/adafruit_tcs34725.py#L240

**Comment by ladyada** [comment]
@microbuilder knows this best!

**Comment by caternuson** [comment]
Thanks for confirming weirdness! I read the datasheet and several ap notes and did not find anything with this math. If you figure out what's it's about, great. Otherwise, may not matter as it will likely go away with updated algorithm suggested by #15.

**Comment by caternuson** [comment]
Fixed with #16
