### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by rdagger** [adafruit/Adafruit_CircuitPython_TCS34725#21]
Both `sensor.color_temperature` and `sensor.lux` throw division by zero errors:

> Traceback (most recent call last):
>   File "code.py", line 7, in <module>
>   File "adafruit_tcs34725.py", line 113, in color_temperature
>   File "adafruit_tcs34725.py", line 314, in _temperature_and_lux_dn40
> ZeroDivisionError: division by zero

Here is my code:
```
from board import SCL, SDA
from busio import I2C
from adafruit_tcs34725 import TCS34725
i2c = I2C(SCL, SDA)
sensor = TCS34725(i2c)
print('Color: ({0}, {1}, {2})'.format(*sensor.color_rgb_bytes))
print('Temperature: {0}K'.format(sensor.color_temperature))
print('Lux: {0}'.format(sensor.lux))
```
I think it may be caused when the color source is too bright.

Also there is a typo on the Adafruit tutorial.  The property `temperature` should be `color_temperature`.  It is incorrect in the docs and the example:  https://learn.adafruit.com/adafruit-color-sensors/python-circuitpython#circuitpython-and-python-usage-3-7

**Comment by caternuson** [comment]
Thanks for spotting the typo in the tutorial, it has been updated.

Can you provide more details on your light source so we can try and reproduce this.

**Comment by rdagger** [comment]
I'm pointing the sensor at illuminated LED's.  It detects the color correctly but the temperature and lux properties throws division by zero.

**Comment by caternuson** [comment]
I'm trying to recreate this by using an LED desk lamp, running your code, and moving the sensor various distances. When I get real close to the lamp, I start getting `None` returns, but no division by zero error.

Can you provide more info on your setup. Are the LEDs single color? Are they really bright? How far away is the TCS from the LEDS? Anything else that might help to recreate this.

We can just add a simple check for the value of `R2` at the point where it's getting the divide by zero. But would be nice to actually be able to recreate this understand how it's getting to the point of having `R2 = 0`.

**Comment by rdagger** [comment]
I'm using single color 5mm LED's (assorted colors).  They are about as bright as the power LED on the Raspberry Pi.  I'm placing the sensor between 1 and 6 inches from the LED.

It doesn't take much to throw an error.  Waving my hand quickly in front of the sensor will cause a division by zero.  Maybe I have a bad sensor.  It works well as long as I don't try to read `sensor.color_temperature` or `sensor.lux`.

Here's some of the variables prior to the crash:

> R: 1, G: 1, B: 1, C: 1
> ATIME: 255
> CPL: 0.00774193
> G1: 0.0
> G2: 0.0
> B2: 0.0
> R2: 0.0
> IR: 1.0
> lux: 0.0

**Comment by rdagger** [comment]
One other thing that might be helpful is that I'm not using any other illumination other than the single color LED's and my work area is dimly lit.  I have the white LED on the board disabled.

**Comment by caternuson** [comment]
@rdagger Sorry for such a long delay in getting back to this. But I've been able to recreate the issue now. I think I was misunderstanding this as a low light issue. I was trying to blast it with bright lights. Pretty simple to recreate the issue by turning off the onboard LED and then covering with a finger.

Catching this is super easy. The bigger question is what to do when it happens. Do you have thoughts on this? My suggestion would be to return `None, None` since essentially what is happening is the light level is too low for a reasonable computation.

There's another suggestion in this PR: #20 , which limits the offending coefficients so that the math at least still works. But would the values actually be reasonable?

**Comment by rdagger** [comment]
@caternuson I like tannewt's recommendation in the above mentioned PR.
Thanks.

**Comment by caternuson** [comment]
OK @rdagger , that's be implemented. Please try the 3.2.3 release version of the library when it becomes available:
https://github.com/adafruit/Adafruit_CircuitPython_TCS34725/releases/tag/3.2.3

**Comment by caternuson** [comment]
Closing due to lack of response. Can re-open if still an issue.
