### ISSUE TITLE
Divide by zero error when LED is off

### ISSUE THREAD

**Issue by dherrada** [adafruit/Adafruit_CircuitPython_TCS34725#4]
When the LED is turned off and a white paper is placed very close to the sensor, the color is pure white so it causes a divide by zero error. I have a kind-of fix to this that makes it not have an error when the color is white but doesn't give a very accurate color temperature.

**Comment by dherrada** [comment]
I looked at the datasheet and couldn't find the formula

**Comment by tannewt** [comment]
User code should catch the zero division errors.
