### ISSUE TITLE
Check interrupt PR on Adafruit_Python_TCS34725 for relevance

### ISSUE THREAD

**Issue by brennen** [adafruit/Adafruit_CircuitPython_TCS34725#7]
See if @all-iver's work here:

https://github.com/adafruit/Adafruit_Python_TCS34725/pull/2

...is something that should be ported across to this library.

**Comment by dherrada** [comment]
Since interrupts aren't supported in circuitpython, I don't believe that PR will be applicable to this library. I'll close this, but if you disagree, I can absolutely reopen it to discuss that.
