### ISSUE TITLE
Add a color property

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_TCS34725#8]
Add a color property that complies with [design guide](https://circuitpython.readthedocs.io/en/latest/docs/design_guide.html#sensor-properties-and-units).

Property name | Python type | Units
-- | -- | --
color | int | RGB, eight bits per channel (0xff0000 is red)

**Comment by process1183** [comment]
Hi @caternuson, may I work on this issue?

**Comment by caternuson** [comment]
Sure! Go for it!

**Comment by caternuson** [comment]
Done! Thanks for the PR!
